---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: elderping-secrets
  namespace: elderping-dev
spec:
  encryptedData:
    db-password: AgB/kNCzvECIt3gfd80llExaKtx2al5pBERw4AzgRdvfrTwVJdYqpoa1qaKLM0fNBKWPAN4SZxHeS7bnwGuYjufnvFGSIEWEyhRhiZLL+ORL13ampGa4vDA7wBHJkB2rffeQ5Mtbr1OSueMjbk2sJ392bHGyjq3kgInmfsDDQM+bUuzS5pYXXnRgwMxo98yY1WlJFAqtiPi8eJb9yT8RpoBE20ICfxbGUq7Ws3XTvI1eBL9wUGUQ9Wyhom84lzZ/K03UIq8zDq3IihI7MFbWi3KATwAs799mKa0Efju4elP5tcuouUfL0K9P/BhWOs7qfV69Z5ZxDNWYWIOAIOamTH4eCQx2B42byPtP9NdHBbKGXHMtarX++aZlMthuRTW6ZXf4Euxnv4dPwMxHkWaVeb5OPl3KnmtwxhuSW6wS+lulfy2kJut6sGO5x+fHI8RTWgiYeq5aD+GAnE9ZA91J0vyh/euqQP45oZ/ceZps0XZMsihUkugw2pL+BOBfkZUlQ8+JUGsn4ifFl6io5z5I/P3rq7+z9c29sM28uJ8Di6IPDrE3+aTKgGvQ29g0aeU4x0fwuyhAaPNJAFnCoADp6So73OF1RhhzxOcwSvWl6YKNfw7jmNL9LOkWMe94HC/TVfcQaT1lOf0Y2B6Hf8TFNzVeNBS4gNlTgB3cTPTFZSOaGKVXIeDeTb6Ik8T1MMQqzuiGlk1IgEAhfpa31OjlWQEAppv9h7IHkQUd/A==
    jwt-secret: AgAeDmPaokpLR/fUljUAnS/ippIK/ZtWGXOy2TVv+tvsWRktNdeiMRb300YeA1H0Avfpjn3ItxG7k0WESwMH0+swLwB4EGw9N3Cn74CGxEAPhukZUAACcSU9XEtIP+NnYI0N0Kwh/CtpbIf+K2ju4EVEE4TDn4TT9PKCcFmGWJ4fksXPwZsHnKjL8ZVY+h1D2hBx68YhUTmkwk5mOkT+obdQ1/21q7KCuECPn4X0FpLfEbeVgjZ7zIwj9Zd57fDs87YXm6MEoAAzWAUCIaUKMlsUQUU+su6hOeH71tYcs8FGzfFXriBnnMq8EA6iemX37N/1NZwQT+hVyeT0CC5KToMtYGQCfxcgeLs4KGH7ETllTSPmvSWU6bKq3s8kwm28JN57KK7TTaTlfA3pI8ra+guq2n+uCK5xHrx/yTqXBiDwYHsvfqPEROUThKEj0CMXyedvNt8R9yPviH5WjO4Dzj5oY3Ld4hG9yFU0Q4aZfRL1LPCdfi0GnjTZIcXNMCyiBUbw9hypv1rlqbiSLoXHj0+MzpXqrS7McRwYtQI7UVhnjdIdoA3ntn9DHfG0pcCtSMrvrG0oZ2DikEUQ0fVLa/NDhZ3GQy6QBNcP1XRG1wKB6cBfupmrZV6ri4GdnhcUt8zo7oEdXbihTFoovf0+eAJYpYji8viM0XTYLetYjqCfHmnJb4fUCLx53+3yuHStNM1H7SJgmfqmw8tqHQBa51f5pTa3
  template:
    metadata:
      name: elderping-secrets
      namespace: elderping-dev
    type: Opaque
