---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: elderping-secrets
  namespace: elderping-prod
spec:
  encryptedData:
    db-password: AgBURHSoIdTY0QJtTX8UHwg3KaQ9K/Cj+Ha6rS9LVRbdfgBsDb1LFmiGKudmPFC5UMP6f2pAsL2fmjiIvhrBLiQuhn9HIoDhyeQFzm4xnKgCQKkbHWrz7104NKwxi7LIpS5B3CvpUiKZo9STNSOJb/p4mNAjljBXabRMU0NLIk53qQ/qxmQiZKiRPBCdNVXqIfUUkxphtd1q0td4YzMR4M8puJAO8KvCQW6lxMLTMEv3CHmBBuQ7w4KUYufcZ7DSBaPtBjUlVWjDw4mry4TqXFixgg17N/u4B2v4IEvdlqWoYMKvpnKyWWMLeEqKkdDlhSoCLvsMZtWVaDtyaSdhNQQDc3eh8/2OsWNWUe2i5DvTD9w7rXCXzg3i8FRNwVtG/3BgT73tt0EzWbH2mtM5OFM0Y0V2JoRNJzr3FYkt2ETwdEOhRu4LHwOxqHgbDbuHUFiWhNs1xWImSXCOAX9uLItCW/ng7zTdKI0uO4HwERg2qo39GgHrFq549jSCeAKU25610iesdHylw6fC+Y6KyTmxTLg54JQ9rtXUuJcLSnXSbpKuPGzVpWHwKfbcjcEpLmw00MNLuxnmnXIGbazkskzwpkSaHI5O+eCKHZgL/XXb73u7K6qTUdsjZrwO1DLWIOrmQDvlp7jY4bI9b5YWdW2uTv98pkm8F1P/tZHcMTh2aBgXFV8xitGwc4CqVatZYZq1NK9OeuJ6qiRwhT/LhD2gHne310o/P3zP3nw=
    jwt-secret: AgACc7anCegXuEzb9XTzJZcgQaUqIIbUO8SAlcT91Dx6WcRD56Nm37tTSmMxWl0FpoujrnEtk/IqwceyDwHKsdu7pe4SPW1ljfrpRERYeRt+LaWUzP+qDa3NMePDg+uhDw39P71Z8w+I/jO1Wo2DKTa8KmG1QcBmJb+jhhJhibmYiNPT8496cde+WXdr9KsEzMTiDwDkcpGYaR1ezxLI8499KB+nlh3SwUQlI7QtKWmkm/XbwLbSaKdM0ObijUXlvqBpkMTlF/etot9EP6f2NYTnG6KJEJF1bdykQtGiFpSX0JTAyuxy3kXr91fpdMIA47F4TmKdJI3/b/feMlB8i+7ny0FBmLjXs4kO68Lo0QDlUrwIzsnuZr/snmH6HK51QJ9Egd5QLNRI4JNWH1Eqq+IFWW135cHUOcVUvDUSfaF10vmCDunwthaTG1eXaN2/UZ30wZOLKYCuYT7GX7jHY2f9/fADsokZZL7bevMLlmsJEXCUR0BfyPMsP4NY79T9hq7m9iO16p+Et+m4MI+Om3o7Q25Wd/+TD+qiM/C5gyyivVaP1K+OuU+Ulk2mm87t1AHVuH4YsDnGhtdjg9o6RQMawgpnp3aHOpqgW687DgkS37FDwjyfNsqY342JmQWSY19jehhoiS5q8nl9X5KdFnjbO50jtaBNE3dcpumKpPgsYDiB197ioOunRxpzDML3nDVJw3780IAkVEW+q8v5w3JDwIO/AA==
  template:
    metadata:
      name: elderping-secrets
      namespace: elderping-prod
    type: Opaque
