apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: {{ .Values.uiService.namespace }}
  labels:
    app: ui-service
spec:
  type: ClusterIP
  selector:
    app: ui-service
  ports:
    - name: http
      port: {{ .Values.uiService.port }}
      targetPort: {{ .Values.uiService.port }}
