authService:
  image:
    repository: arunnsimon/elderpinq-auth-service
    tag: prod-latest
  replicas: 2
  port: 3000
  namespace: elderping-prod
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilization: 80
    targetMemoryUtilization: 80
  env:
    dbHost: auth-db
    dbPort: "5432"
    dbUser: postgres
    dbName: users_db
    port: "3000"
  secrets:
    dbPasswordSecret: elderping-secrets
    dbPasswordKey: db-password
    jwtSecretSecret: elderping-secrets
    jwtSecretKey: jwt-secret
